version: '3'
services:
  electrum:
    image: electrum-nmc
    container_name: nmc
    ports:
      - 127.0.0.1:8334:8334
    environment:
      - ELECTRUM_USER=namecoin
      - ELECTRUM_PASSWORD=namecoinz
    volumes:
      - ./config/electrum-nmc:/data/electrum-nmc
